# crd.yml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: airflowdags.operators.rolanddb.github.io
spec:
  group: operators.rolanddb.github.io
  versions:
    - name: v1 # it's possible to provide multiple versions of a CRD
      served: true # it's possible to disable a CRD
      storage: true # there can be multiple versions but only one can be used to store the objects
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name: 
                  type: string
                  minLength: 3
                  maxLength: 42  
                filecontent:
                  type: string
                  format: byte # base64 encoded
  scope: Namespaced # resources can be namespaced or available for the whole cluster
  names:
    plural: airflowdag
    singular: airflowdags
    kind: AirflowDag # this name is being used in manifests
    shortNames: # these short names can be used in the CLI, e.g. kubectl get er
    - afd
